export type CoincheckCoinType =
  | "btc"
  | "eth"
  | "etc"
  | "lsk"
  | "xrp"
  | "xem"
  | "bch"
  | "mona"
  | "iost"
  | "enj"
  | "chz"
  | "imx"
  | "shib"
  | "avax"
  | "fnct"
  | "dai"
  | "wbtc"
  | "bril"
  | "bc"
  | "doge"
  | "pepe"
  | "mask"
  | "mana"
  | "grt";

export type BinanceCoinType = "BNBBTC" | "BNBETH" | "BNBJPY" | "ADABNB" | "SOLBNB" | "DOTBNB" | "TRXBNB" | "XRPBNB" | "AVAXBNB" | "SUIBNB" | "LTCBNB" | "HBARBNB" | "POLBNB" | "LINKBNB" | "BCHBNB" | "CHZBNB" | "ETCBNB" | "AXSBNB" | "SEIBNB" | "NEARBNB" | "CYBERBNB";